{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(PizzaFactory_ms{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PIzza Latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(service_ms{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Creation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pizza_failure{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Creation Failure"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(memory_percentage{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Memory"
    },
    {
     "expr": "rate(cpu_percentage{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Sales per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Sold"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(login_success{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(login_failure{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(user_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "HTTP Request per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "All"
    },
    {
     "expr": "rate(request_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(request_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Post"
    },
    {
     "expr": "rate(request_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(request_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Put"
    }
   ]
  }
 ]
}